# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job-resource-configuration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='job-resource-configuration.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\007grpc/pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n job-resource-configuration.proto\":\n\x11GetByJobIdRequest\x12\r\n\x05jobid\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x65\x66\x61utexecutor\x18\x02 \x01(\t\"R\n\x12GetByJobIdResponse\x12\x11\n\tidrequest\x18\x01 \x01(\x03\x12)\n\x0fresourceCreated\x18\x02 \x01(\x0b\x32\x10.ResourceCreated\"/\n\x0fResourceCreated\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08provider\x18\x02 \x01(\t2Z\n\x1fJobResourceConfigurationService\x12\x37\n\nGetByJobId\x12\x12.GetByJobIdRequest\x1a\x13.GetByJobIdResponse\"\x00\x42\tZ\x07grpc/pbb\x06proto3'
)




_GETBYJOBIDREQUEST = _descriptor.Descriptor(
  name='GetByJobIdRequest',
  full_name='GetByJobIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobid', full_name='GetByJobIdRequest.jobid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='defautexecutor', full_name='GetByJobIdRequest.defautexecutor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=94,
)


_GETBYJOBIDRESPONSE = _descriptor.Descriptor(
  name='GetByJobIdResponse',
  full_name='GetByJobIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idrequest', full_name='GetByJobIdResponse.idrequest', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resourceCreated', full_name='GetByJobIdResponse.resourceCreated', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=178,
)


_RESOURCECREATED = _descriptor.Descriptor(
  name='ResourceCreated',
  full_name='ResourceCreated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ResourceCreated.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='provider', full_name='ResourceCreated.provider', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=227,
)

_GETBYJOBIDRESPONSE.fields_by_name['resourceCreated'].message_type = _RESOURCECREATED
DESCRIPTOR.message_types_by_name['GetByJobIdRequest'] = _GETBYJOBIDREQUEST
DESCRIPTOR.message_types_by_name['GetByJobIdResponse'] = _GETBYJOBIDRESPONSE
DESCRIPTOR.message_types_by_name['ResourceCreated'] = _RESOURCECREATED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetByJobIdRequest = _reflection.GeneratedProtocolMessageType('GetByJobIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBYJOBIDREQUEST,
  '__module__' : 'job_resource_configuration_pb2'
  # @@protoc_insertion_point(class_scope:GetByJobIdRequest)
  })
_sym_db.RegisterMessage(GetByJobIdRequest)

GetByJobIdResponse = _reflection.GeneratedProtocolMessageType('GetByJobIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETBYJOBIDRESPONSE,
  '__module__' : 'job_resource_configuration_pb2'
  # @@protoc_insertion_point(class_scope:GetByJobIdResponse)
  })
_sym_db.RegisterMessage(GetByJobIdResponse)

ResourceCreated = _reflection.GeneratedProtocolMessageType('ResourceCreated', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCECREATED,
  '__module__' : 'job_resource_configuration_pb2'
  # @@protoc_insertion_point(class_scope:ResourceCreated)
  })
_sym_db.RegisterMessage(ResourceCreated)


DESCRIPTOR._options = None

_JOBRESOURCECONFIGURATIONSERVICE = _descriptor.ServiceDescriptor(
  name='JobResourceConfigurationService',
  full_name='JobResourceConfigurationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=229,
  serialized_end=319,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetByJobId',
    full_name='JobResourceConfigurationService.GetByJobId',
    index=0,
    containing_service=None,
    input_type=_GETBYJOBIDREQUEST,
    output_type=_GETBYJOBIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_JOBRESOURCECONFIGURATIONSERVICE)

DESCRIPTOR.services_by_name['JobResourceConfigurationService'] = _JOBRESOURCECONFIGURATIONSERVICE

# @@protoc_insertion_point(module_scope)
